emacs-ng/emacs-ng

- rust_src/remacs-macros/lib.rs
- rust_src/src/lib.rs
- rust_src/src/lisp.rs
- rust_src/src/remacs_sys.rs
This PR repairs the ability to use the #[lisp_fn] macro to define Rust functions callable from emacs. Previously in remacs, we called "xmalloc", and left the pointer linger on the heap for the duration of the program. Changes to the emacs build process (including pdump and unexec) have made this no longer viable. Instead I have opt'd to use the MaybeUninit construct to make an actual aligned and uninitialized struct that we can fill with data and hand off to the C layer.  
Basic functionality test can be performed via the following patch applied to this branch:
```
diff --git a/rust_src/src/example.rs b/rust_src/src/example.rs
new file mode 100644
index 0000000000..d91ad58bf2
--- /dev/null
+++ b/rust_src/src/example.rs
@@ -0,0 +1,9 @@
+use lazy_static::lazy_static;
+use …
```
> Fixing lisp_fn macro functionality to work with new pdumper logic.

- configure.ac
- rust_src/remacs-bindings/src/main.rs
Addresses https://github.com/remacs/emacs-webrender/issues/14
Emacs commit https://github.com/remacs/emacs-webrender/commit/365dad197bac5deec9244fd9c189d23c46c99b31 introduced an optimization where the inline functionality is implemented via the keyword "static" instead of "inline". This causes problems for bindgen, resulting in bindgen not generating appropriate rust bindings. In addition, using "static" will not enable us to link against those functions and call them from Rust. 
By defining EMACS_EXTERN_INLINE in the C pre-processor, we can get the behavior we had in remacs in terms of inline functions. 
Its unfortunate that this will likely cause a performance regression, however I can't think of a better solution without reimplementing these inline functions in Rust. 
Comment from …
> Fixing ability to use inline functions in rust layer

- rust_src/remacs-macros/lib.rs
Currently to use lisp_fn, you need to include `use lazy_static::lazy_static;` in your module. This PR removes this requirement via a custom use alias per invocation of lisp_fn.
> Removing need for 'use lazy_static' in a module that uses lisp_fn

- configure.ac
- rust_src/Cargo.toml.in
- rust_src/build.rs
- rust_src/src/eval_macros.rs
- rust_src/src/frame.rs
- rust_src/src/lib.rs
- rust_src/src/wrterm.rs
- rust_src/wrapper.h
- src/dispextern.h
- src/emacs.c
- src/frame.h
- src/image.c
- src/lisp.h
- src/termhooks.h
- src/window.c
- src/wrgui.h
- src/wrterm.h
- src/xfaces.c
* Add new option `--with-webrender` in `configuration.ac` 
* Add new cargo feature `windows-system-webrender` in rust_src
It's buildable while the result binary isn't runnable.
> Add a `webrender` window system

- rust_src/src/javascript.rs
- rust_src/src/prelim.js
- test/js/basicLisp.js
Results: Measurable improvement for JS -> Lisp Performance in multiple cases. 
All tests are based on 10,000 iterations 
| Test              | Pre-PR        | Post-PR  | % Improvement
| ------------- |:-------------:| ---------:| ------:|
| T1                | 775ms         |   356ms  |  54% |
| T2                | 45ms           |   8ms      | 82%  |
| T3                | 70ms           |   27ms    | 61%  |
| T4                | 32ms           |   22ms    | 31%  |
T1: (with-temp-buffer (insert "foo")) and JS equivalent
T2: (conat "foo" "bar") and JS equivalent 
T3: (intern "foo") and JS equivalent
T4: (insert "Hello World") and JS equivalent 
Lessons Learned:
* Using WeakRef caches is a powerful tool in the cases of tight loops calling lisp functions with similar arguments. Previously, …
> JS Performance Improvements

- .gitmodules
- README.md
- rust_src/Cargo.lock
- rust_src/Cargo.toml.in
@harryfei had a good recommendation to move to using [this cargo feature](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) instead of using a git submodule. In testing this feature, it seems like nothing but upside.
> Removing deno submodule for ease-of-use

- configure.ac
- src/Makefile.in
* Fixes issue where you would need to perform a clean build to get new `#[lisp_fn]` functions added to a release build. 
* Fixes issues where `sudo make install` would not work when cargo was installed via rustup in ~/.cargo 
* Fixing issue where the output of emacs-ng and remacs-lib were both named `libremacs_lib`, which caused bizarre issues with make rebuilding things when they weren't out of date.
> Fixing up issues with build system

- rust_src/src/javascript.rs
- rust_src/src/prelim.js
* Fixing issue where if a user sets a property on a string literal, it would apply to all cases of that string literal due to the string cache.
* Fixing issue where a JS parse error would cause the runtime to reset. 
* Adding `lisp.make.string` to allow the user more control over lisp string allocation. 
* Allow user access to the specialForms object via `lisp.specialForms`
> Fixing String Cache, JS Runtime Restart Errors

- rust_src/crates/lisp/src/frame.rs
- rust_src/crates/lisp/src/lib.rs
- rust_src/crates/lisp/src/obarray.rs
Latest push on master seems to have broken --enable-rust-debug (due to a linker error that is optimized into being a non-issue in an optimized build), and --without-x (due to some assumptions about fields in C structs that are compiled out in --without-x).
> Fix Rust debug builds and '--without-x' builds.

- rust_src/Cargo.lock
- rust_src/src/javascript.rs
- rust_src/src/prelim.js
- src/alloc.c
In current emacs-ng, once you initialize JavaScript, the event loop is always polling at `js-tick-rate` intervals. However, this is not needed if there are no pending module imports or promises. This just wastes CPU cycles and battery power. This patch brings us to a state of "you pay for what you use", and reduces timer usage. 
Instead, we now tick only when there are pending promises, and we increase the tick rate from 0.1 to 0.001. This addresses https://github.com/emacs-ng/emacs-ng/issues/105, and brings async performance inline with deno native, who has a much faster event loop. The user still has the ability to control the js-tick-rate if they want to lower it.
If people on lower end machines complain about 0.001 we can evaluate that default. 
Callout - Before, to cleanup lisp …
> Reduce unneeded polls to event loop

- rust_src/src/javascript.rs
The default tick rate of 0.001 now seems to fast for me and is causing hitching. I'm going to lower it, and in an attempt to solve the issue, expose the ability to set the tick rate directly.
> Allow tick rate to be controlled from scripting layer directly

- rust_src/Cargo.lock
- rust_src/Cargo.toml.in
- rust_src/src/webrender_backend/output.rs
upgrade `glutin` to 0.26. It fixes broken wayland support.
> webrender: upgrade glutin to fix #123.

- rust_src/Cargo.lock
- rust_src/src/javascript.rs
Previous improvements to our event loop logic brought us near Deno performance for Async I/O operations, despite the fact that our event loop ticks less often. However, I found cases where emacs wouldn't tick our loop for various reason that would led to subpar performance compared to Deno.
Now I have a new approach, in which by default we loop less often, but so long as we have pending actions, we move the event loop forward in a tight loop. This improves Async I/O performance for file operations without an apparent increase in CPU usage.
While not included, I weighed adding a max time in the tight loop (i.e. do not exceed 16ms within the tight loop) to prevent hitching, but chose not to include that in this PR. It will be simple to add if we go that route. 
I've given the user control …
> Improvement of JS Event Loop Logic

- adv-features.md
Making the command explicit helps beginners.  The code is not valid
js, so `eval-js-buffer` would error.
> Add explicit command to run the example code

- rust_src/src/javascript.rs
The delay isn't consistent, but can happen is the right set up inputs line up. It should be a simple fix.
> Fixing issue where event would be delayed for an M-x function

- getting-started.md
Making usage of the ":no-check t" option more clear. I've also moved it to after what we show the user what a TS error looks like.
> Updating wording in Getting Started

- configure.ac
- rust_src/Cargo.toml.in
- rust_src/src/javascript.rs
- rust_src/src/javascript_stubs.rs
- rust_src/src/lib.rs
- rust_src/src/parsing.rs
Fixes https://github.com/emacs-ng/emacs-ng/issues/130
This PR has made me really want to refactor `#[lisp_fn]`. Unless I'm missing something, it seems like it's really painful to deal with lisp_fn combined with condition includes, since docstring.rs will just parse anything it sees as a rust file, even if it's not included as a module in lib.rs
> Adding configure --without-javascript option

- getting-started.md
- rust_src/src/javascript.rs
- rust_src/src/prelim.js
This PR adds a very requested feature, which is the equivalent of M-: but for JavaScript. This also adds `eval-js-literally`, which will actually return the value of the JavaScript expression, unlike eval-js-* which always returns nil. This will auto-translate proxys, meaning that things like:
`(eval-js-literally "lisp.current_buffer()")` works how you would hope it does - it will actually return the current buffer as a lisp object. 
It seems like we should bind `eval-js-expression` to a key binding, but I'm unsure what a good default, if any, would be. I'm open to suggestions. 
These functions will ONLY work with JavaScript. Adding TS support won't be hard, but I want to wait until https://github.com/emacs-ng/emacs-ng/issues/118 lands, because Deno 1.7 reworked their interface to compile …
> Adds eval-js-expression and eval-js-literally

- README.md
Since we have more conversations on gitter, I think it makes sense to link to the channel overview instead of the community room. I added a webrender room(https://gitter.im/emacsng/webrender). Feel free to open additional rooms.
> gitter: link to room overview instead of community

- rust_src/src/javascript.rs
- rust_src/src/parsing.rs
- test/js/errors.js
- test/js/main.js
Marking this as WIP as I still need to write some tests for this patch. I also want to improve the logic for parsing::deser and parsing::ser. One returns a result, and one returns an option - it's messy in general. Both can error on certain inputs, which causes issues. 
This patch addresses some real edge cases with error handling, like if an error happens when you are in a JS -> LISP -> JS -> LISP -> JS -> LISP type callstack.
> Fix JS error propogation in JS defuns. Fix panic when calling json() on functions. 

- using-deno.md
The previous link was landing to a non-existing internal page.
> Fix typo in Deno's homepage link

- rust_src/src/javascript.rs
- test/js/errors.js
Repreoduction:
```lisp
(eval-js-literally "throw new Error('err')") 
```
Above will not throw on current. In addition, this will cause a panic on current:
```js
lisp.eval_js_literally('3')
```
Both are fixed by this patch
> Fixing errors not being thrown by eval-js-literally

- rust_src/src/javascript.rs
- test/js/basicLisp.js
- test/js/bootstrap.el
- test/js/errors.js
- test/js/helloWorld.js
- test/js/main.js
- test/js/webAsm.js
- test/js/webWorkers.js
~~WIP, dependent on https://github.com/emacs-ng/emacs-ng/pull/170 landing first~~
I might add things to this list between now and that PR landing, but this is my starting off point. This PR shouldn't actually change any behavior, it should just be a refactor. 
Goals:
> javascript.rs cleanup

- rust_src/src/webrender_backend/term.rs
Running with `--with-webrender`, emacs would panic on startup with an "unwrap on a none value" message referencing the `CursorMoved` event handler. I'm not well-versed in Rust but it seems like there was an assumption in the code that `top_frame.as_frame()` would be something like `Option<LispFrameRef>` but it was in fact `None`. It looks like some of the other event handlers handled this issue in the way that I've now done so in this commit. This change has now allowed me to build a working emacs with webrender, which is quite cool.
> Return early from CursorMoved if top_frame is none

- README.md
Current link to `/features` 404s, based off the nav on the site it appears the path should be `/main-features`
> Docs: Fix features link in README.md

- docs/getting-started.md
With `8` installed I got the error 
```
Please try installing libgccjit or similar package.
If you are sure you want Emacs compiled without elisp native compiler, pass
--without-nativecomp
to configure.
```
with `9` installed it works
> fix required version

- .github/workflows/release.yml
- build_emacs_ng.sh
Allow to automatically create deb release package based on weekly prerelease and tag based stable release.
The uploaded deb package is named with following convention:
- Weekly prerelease: `emacs-ng_0.0.<sha>-1_amd64.deb`
- Stable release for tag `vx.y`: `emacs-ng_x.y-1_amd64.deb`
Todo:
- Don't create new weekly release if there's no new commit?
- Support more package format?
> ci: auto generate release deb package

- docs/faq.md
- docs/getting-started.md
- docs/main-features.md
I looked at the documentation in `docs` and the link was broken.
Corrected, and removed trailing spaces.
> Doc link fix, remove trailing space

- configure.ac
- docs/ng-module.md
- mkdocs.yml
- rust_src/Cargo.toml.in
- rust_src/build.rs
- rust_src/src/lib.rs
- rust_src/src/ng_module.rs
Since we want to be ABI-compatible with dynamic modules written for vanilla Emacs, we don't add more functions to `emacs_env`.
Instead, we provide a registry of named native functions that can be looked up at run time. We call these `ng-module functions`. Unlike normal module functions, they have globally stable addresses, which should be looked up once, at module load time (in `emacs_module_init`).
I made a [quick prototype](https://github.com/ubolonton/emacs-tree-sitter/commit/381cf5cdd300bf2df347f53f163d0d9d59635c36) that shows how to use this in `emacs-tree-sitter`. Some quick-n-dirty tests show up to 2x speedups.
> Enable dynamic modules to directly read current buffer's text

- .github/workflows/release.yml
- build_emacs_ng.sh
Make the release pipeline more efficient by:
- Don't attempt to build a new release if the code has not changed from the last release
- Don't install `rust` in release pipeline anymore since it will be installed by the script later.
- Fix bug in build script that makes the `configure` not effective, making `native-compilation` Emacs not being built.
- Switch from `libgccjit-10` -> `libgccjit-9` for better compatible with older distro and also include more libs as deps
> ci: make release pipeline more efficient

- .github/workflows/release.yml
Minor fix to use current repository in release CI instead of hardcoding
> ci: use github.repository instead of hardcode in release

- generate-docs.sh
Hi @brotzeit 
this is a small script + info on how to compile locally the [documentation for emacs-ng](https://emacs-ng.github.io/emacs-ng). I find it useful to iterate when I'm editing the documentation before submitting a patch.
It's just the content of the [Github action](https://github.com/emacs-ng/emacs-ng/blob/45403b76ba72b9273d9022faa9f12d4ab0c03927/.github/workflows/docs.yml#L15-L19) dumped in a file for easier reach.
Would that help? Or else, where should this be? 
thanks for checking this out!
> Add instructions to compile emacs-ng docs

- flake.lock
- flake.nix
to prevent:
```bash
error: hash mismatch in fixed-output derivation '/nix/store/502ysqvil5rnqaasmvkrysw0h5ywzk3m-remacsSrc-vendor.tar.gz.drv':
specified: sha256-1ELtwJeAyIO1I35Its/pwsA+/d7lHDighSFPFbIBXIQ=
got:    sha256-Tn1sbMSIjy+VTId5lrlw8eeBFgIiAtQoSv6c+VDvmfI=
```
> flake.nix: remacsSrc hashsum fix

- .dockerignore
- docker/Dockerfile.debian
- docs/docker.md
- docs/release.md
- mkdocs.yml
This will add a Dockefile to build a .deb for Debian.
It works but I'll iterate a bit more on this to see if I can slim this down a bit
(also suggestions and reviews welcome)
Ref: #235
> Add Dockerfile to build for Debian

- configure.ac
- rust_src/Cargo.lock
- rust_src/Cargo.toml.in
- rust_src/src/webrender_backend/draw_canvas.rs
- rust_src/src/webrender_backend/image.rs
- rust_src/src/webrender_backend/mod.rs
- rust_src/src/webrender_backend/output.rs
- rust_src/src/webrender_backend/term.rs
- rust_src/src/wrterm.rs
- src/dispextern.h
- src/image.c
- src/wrterm.h
Supports png, jpeg, git, tiff and pbm.
Re-implement image handlers in rust with [`image`](https://github.com/image-rs/image) crate instead of reusing the terrible codes in `GNU emacs`.
> webrender: support image rendering

- autogen.sh
The rust relating code in autogen.sh refers to variable `remacs_version` which is not defined, causing output to look like:
```
$ ./autogen.sh                                                              
Checking Rust toolchain install ...
error: no default toolchain configured
error: no default toolchain configured
error: no default toolchain configured
Remacs currently requires Rust toolchain version .
Run 'rustup install '.
```
> Fix typo in autogen.sh

- rust_src/crates/js/src/prelim.js
:wave:   This PR exposes `define-derived-mode` as special forms like `define-minor-mode` in order to create a major mode derived
> Add define_derived_mode 

- .github/workflows/release.yml
- build_emacs_ng.sh
Fix build script to not use obsoleted `checkinstall` (which hangs recently) and switch to `dpkg-deb` instead to create deb file
> build_emacs_ng: fix build scripts

- rust_src/crates/webrender/src/font.rs
- rust_src/crates/webrender/src/output.rs
Make macOS porting easier for font related code.
> webrender: simplify font creation.

- flake.nix
- rust_src/crates/webrender/src/display_info.rs
- rust_src/crates/webrender/src/event_loop.rs
- rust_src/crates/webrender/src/frame.rs
- rust_src/crates/webrender/src/output.rs
- rust_src/crates/webrender/src/term.rs
- rust_src/crates/webrender/src/wrterm.rs
closes https://github.com/emacs-ng/emacs-ng/issues/344
An known issue: After closing the second window, the wayland-client library throw a error after random time. I think it related to winit's wayland library.
It works well on X11.
> webrender: multiple frame

- .gitmodules
- configure.ac
Link macOS Metal framework only when `--without-javascript` is not used.
Otherwise there is warning flooding when compiling
```
clang: warning: -Wl,-framework: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,Metal: 'linker' input unused [-Wunused-command-line-argument]
```
---
Also included an irrelevant small change regarding git submodule
- Make git submodule ignore dirty
> build: Link Metal only when need

- build_emacs_ng.sh
Motivation:
* parity with traditional emacs release builds
* improved performance (-O2), debuggability without performance loss (-g)
TESTED: manual invocation of ./configure line succeeded on my machine (debian x64 5.10.40).
for comparison, debian emacs(-lucid) 27.1 `system-configuration-options` value is:
```
--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib …
```
> Add CFLAGS `-O2 -g` to release build script.

- rust_src/crates/webrender/src/event_loop.rs
- rust_src/crates/webrender/src/output.rs
- rust_src/crates/webrender/src/wrterm.rs
- rust_src/ng-bindgen/src/main.rs
Fixed two minor webrender issues:
- Terminal Emacs (`-nw`) not working on macOS
- Need manually pass `DISPLAY=${hostname}` to open a GUI frame on macOS
Copied the logic from [PGTK](https://github.com/masm11/emacs/blob/pgtk/src/pgtkfns.c#L2127-L2130)
> webrender: use thread_select when running without window system

- README.md
- docs/package-management.md
- mkdocs.yml
@declanqian maybe it's better to keep the readme short and only give an overview of the available features and have more detailed docs in the wiki. What do you think ?
> introduce wiki section for built-in elisp packages

- configure.ac
- lisp/wr-fns.el
- rust_src/Cargo.lock
- rust_src/Cargo.toml.in
- rust_src/build.rs
- rust_src/crates/emacs/src/eval_macros.rs
- rust_src/crates/emacs/src/lib.rs
- rust_src/crates/emacs/src/xdisp.rs
- rust_src/crates/webrender/Cargo.toml
- rust_src/crates/webrender/build.rs
- rust_src/crates/webrender/src/color.rs
- rust_src/crates/webrender/src/wrterm.rs
Wrote some rust/lisp, integrating [WebRender capture infrastructure](http://kvark.github.io/webrender/debug/ron/2018/01/23/wr-capture-infra.html) using
Transient interface. Didn't solve any existing problems here.
Only trying to get myself comfortable with the codebase.
Some notable changes:
- Added `webrender-head-rev` lisp var which reflects current webrender version in use.
- Add `message!` macro to send non-error text to Emacs echo area, as a complement to
`error!`.
- Moved webrender auto generated code to webrender/build.rs, aka `colors.rs`. Also newly
added `webrender_revision.rs`.
I think we should avoid generating code for other crates from `rust_src/build.rs`.
Also, did we misused [Cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) for rust_src? Can't …
> webrender: integrate wr capture infra

- docs/build/nix-develop.md
Nix 2.4 was recently released. Flakes do not require a development version of nix anymore
> Update nix flake instructions

- docs/build/docker.md
This PR is in my humble opinion. Please check and add comment.
I updated the document for building on docker ( https://emacs-ng.github.io/emacs-ng/build/docker/ ).
In my environment, the step copying `.deb` from container is not working.
The summary I updated is below.
- fix `.deb` file path
- It is not in `/emacs-ng/` but in `/src/`.
- fix the container doesn't keep running
- `docker run -d` doesn't keep running, I added the tail command.
- Remove container id
- Container name ( `delete-me` ) can be used.
- add `--rm` argument and change `docker rm` to `docker stop`
- without stopping container, the `docker rm` should be failed.
> Fix docs for building on docker

- flake.nix
I'm on aarch64-darwin building as x86_64-darwin
> fix: wrong sha256 sum of emacsngLibDeps

- Cargo.in
- rust_src/crates/webrender/Cargo.in
- rust_src/crates/webrender/src/font.rs
- rust_src/crates/webrender/src/font_db.rs
- rust_src/crates/webrender/src/term.rs
- rust_src/lib.rs
- src/emacs.c
- src/lisp.h
So, before. We use fontdb load_system_fonts to load fonts to use while using fontkit to find
the family name to use.
But fontkit has full fontconfig support while fontdb uses hard-coded path, which would cause problem when fontkit return a name  hasn't been loaded by fontdb.
This patch uses my patched font_loader to get system font dirs for fontdb to use on Unix. Also it
uses font_loaders fontconfig to query font names.
> Add native fontconfig support

- rust_src/crates/webrender/src/term.rs
- src/frame.c
closes #502 .
I've also dropped the explicit test for `HAVE_PGTK` here, as it doesn't make sense to call `wrterm` functions unless we have webrender.  I don't know if you can still build non-webrender pgtk with this fork, but it seems worth leaving the possibility in place if we can.
*WHY* isn't it documented anywhere that frame->parent_frame being non-nil is the test for a graphical frame?!  Took me a good twenty minutes to persuade myself it really was always true.
More interestingly, why did this work before?  `emacs -nw` always failed if it couldn't get the graphical display, but other than that it was fine.  This way it works over ssh again :D
> fix: avoid window system when running in terminal

- Cargo.in
- Cargo.lock
Upstream tao has a (trivial) fix for unavailable primary monitor on linux. We're just waiting for them to release 0.18.2.  In the meantime this fixes resizing/etc on linux if primary_monitor fails.
> fix(wr): use upstream tao for primary_monitor() fix.

- rust_src/crates/webrender/src/cursor.rs
- rust_src/crates/webrender/src/draw_canvas.rs
- rust_src/crates/webrender/src/font.rs
- rust_src/crates/webrender/src/frame.rs
- rust_src/crates/webrender/src/gl/context_impl/glutin.rs
- rust_src/crates/webrender/src/gl/context_impl/gtk3.rs
- rust_src/crates/webrender/src/gl/context_impl/surfman.rs
- rust_src/crates/webrender/src/input.rs
- rust_src/crates/webrender/src/output.rs
- rust_src/crates/webrender/src/term.rs
- rust_src/crates/webrender/src/util.rs
- rust_src/crates/webrender/src/window_system/pgtk/frame.rs
- rust_src/crates/webrender/src/window_system/pgtk/output.rs
- rust_src/crates/webrender/src/window_system/winit/frame.rs
- rust_src/crates/webrender/src/window_system/winit/term.rs
- src/frame.c
- src/pgtkterm.c
- src/pgtkterm.h
- src/webrender_ffi.h
This PR makes the frame/wrfont size (pixel_width/pixel_height) at scale 1 while the winit window and WR OpenGL surface size at real scale. We scale the produced glyphs from Emacs redisplay all together just before sending them to WebRender.
- Reverted previous font changes for scaling 
- Also fixed WR/PGTK child frame.
[2023-03-11-22:29:45-screenshot](https://user-images.githubusercontent.com/22841038/224514293-521d09e1-e115-41b1-8eaf-0054f81d0c84.png)
[2023-03-11-22:29:59-screenshot](https://user-images.githubusercontent.com/22841038/224514298-69bbb96b-9a58-4fc5-b605-2c68333362be.png)
(these lines appear as I navigate the helm buffer and clearly should be rendered in it)
[2023-03-11-22:31:51-screenshot](https://user-images.githubusercontent.com/22841038/224514347-b53b528e-e27b-41ad-aa51-5 …
> WR: Scale glyphs all together just before rendering

- rust_src/crates/webrender/src/wrterm.rs
This is just a typo I think. It's called from `lisp/frame.el`.
> fix: display-monitor-attributes-list

- rust_src/crates/emacs/src/lisp.rs
- rust_src/crates/webrender/src/draw_canvas.rs
- rust_src/crates/webrender/src/font.rs
- rust_src/crates/webrender/src/window_system/winit/frame.rs
- rust_src/crates/webrender/src/wrterm.rs
- src/font.c
- src/font.h
- src/pgtkfns.c
- src/xfaces.c
WebRender's [wr_glyph_rasterizer](https://github.com/servo/webrender/tree/master/wr_glyph_rasterizer) currently is unable to handle color fonts like "Noto Color Emoji". See [#498](https://github.com/emacs-ng/emacs-ng/issues/498). We disable "Noto Color Emoji" for WR renderer in this PR.
Also included some code refactor:
- Added debug trait for `LispObject`.
So we can debug `LispObject` obj with `println!({obj:?})`
- Added `From/To<String>` trait for `LispObject`.
- Implemented overstrike face for WR renderer.
- rename `ttf_parser` to `tffp` according to their [c-api](https://github.com/RazrFalcon/ttf-parser/blob/master/c-api/ttfparser.h)
> Wr disable noto color emoji

- flake.nix
I wanted to check if this product is something for me, so I tried to run:
```
nix run github:emacs-ng/emacs-ng
```
I forked the repo to check what error the build would give me if I try to compile this program on my machine.
There was no error and everything compiled just fine. I noticed #336 but that error showed up with the makefile if I'm not mistaken.
Nix is reproducible so you can test it yourself ;)
It's my first time here, feedback is appreciated :))
> Add aarch64-darwin to flake

- .gitignore
Hi all,
NixOS users often use direnv to load and unload the Nix dev shell.
Direnv creates a cache of your shell, which is very handy, but it should not be pushed to the repository.
This PR adds the ```.direnv``` directory to the ```.gitignore```.
> Ignore .direnv

- Cargo.lock
- configure.ac
- rust_src/crates/winit-term/Cargo.toml
- rust_src/crates/winit-term/build.rs
- rust_src/crates/winit-term/src/fns.rs
- rust_src/crates/winit-term/src/frame.rs
- rust_src/crates/winit-term/src/term.rs
- rust_src/wrapper.h
- src/frame.h
- src/termhooks.h
- src/winitterm.h
* Using winit event_loop raw fd on linux
Which fixed the key pressed not working
* Add lisp fn `winit_raw_window_handle_name`
Which is useful for inspecting which display(wayland/x11 etc) is in use currently
* Enable Cargo shallow clones
> Use winit event_loop raw fd on linux

- rust_src/crates/winit-term/src/frame.rs
- rust_src/crates/winit-term/src/term.rs
- src/frame.c
- src/frame.h
* make emacs -fs working for winit term
* init baud-rate for winit term (see #332 [comments](https://github.com/emacs-ng/emacs-ng/issues/332#issuecomment-1994249955))
> Fixes for winit frame
