emacs-ng/emacs-ng

rust_src/src/javascript.rs
=> Adding Async File I/O for module loading / Adding eval-js-buffer and eval-js-region

rust_src/src/remacs_sys.rs
Addresses issue discovered in https://github.com/emacs-ng/emacs-ng/issues/49
=> Fixing OSX Build Error

rust_src/src/javascript.rs
Adding the following:
>:ts-config PATH - Specifies the file path to your custom tsconfig json file see https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
> :no-check t - disables TypeScript type checking. Can be used to gain performance when the user does not want or require typechecking
> :no-remote t - disables the import of remote files via import statements. This option still allows network options via calls to fetch(...)
=> Adding additional options for js-initialize

README.md
I can't get the "R" to be lower case. Any idea ?
=> add reddit badge

.github/workflows/test.yml, .gitignore, README.md, admin/format-rust.sh, rust_src/Cargo.toml, rust_src/crates/lisp/src/lisp.rs, rust_src/src/parsing.rs, rust_src/src/webrender_backend/draw_canvas.rs, test/js/bootstrap.el
=> configure github ci

test/js/bootstrap.el
Should fix https://github.com/emacs-ng/emacs-ng/issues/87
=> Fixing js runtime tests

rust_src/src/javascript.rs
If you define a function in JavaScript that looks something like:
```js
lisp.defun({
name: "foo",
func: () => setInterval(() => console.log("Bar"), 0)
});
```
It will cause a sometimes cause a panic, because our setInterval may attempt to immediately call into the tokio runtime, despite the fact that we haven't entered the tokio runtime. There is no reason not to enter the runtime anytime we call into JS.
=> Fixing Panic when sometimes calling interactive functions

rust_src/Cargo.lock, rust_src/Cargo.toml.in, rust_src/src/git.rs, rust_src/src/lib.rs
until we found the reason for #111
=> disable git2 for now

lisp/emacs-lisp/emacs-ng.el, lisp/loadup.el
Addresses https://github.com/emacs-ng/emacs-ng/issues/107
=> Adding (featurep 'emacs-ng)

rust_src/Cargo.toml.in, rust_src/crates/lisp/Cargo.toml, rust_src/crates/lisp/src/window.rs, rust_src/src/webrender_backend/cursor.rs, rust_src/src/webrender_backend/display_info.rs, rust_src/src/webrender_backend/draw_canvas.rs, rust_src/src/webrender_backend/event.rs, rust_src/src/webrender_backend/keyboard.rs, rust_src/src/webrender_backend/mod.rs, rust_src/src/webrender_backend/output.rs, rust_src/src/webrender_backend/term.rs, rust_src/src/webrender_backend/texture.rs, rust_src/src/wrterm.rs
* handle keyboard event
* scroll window support
* show window cursor
=> webrender: handle keyboard event

README.md, faq.md
I've gotten these questions through various mediums, sometimes multiple times. Seems like a good point to add an FAQ.
=> Adding a FAQ for the project

rust_src/Cargo.lock, rust_src/src/javascript.rs, rust_src/src/parsing.rs
Fixes https://github.com/emacs-ng/emacs-ng/issues/114
=> Fix panic on string initalization, improve write performance

rust_src/src/webrender_backend/draw_canvas.rs, rust_src/src/webrender_backend/output.rs, rust_src/src/webrender_backend/term.rs, rust_src/src/wrterm.rs
- window support resizable
- show window title
- render wave underline
=> webrender: more window stuffs

rust_src/src/webrender_backend/draw_canvas.rs
* fix background fill bug
* fix header line height
=> webrender: fix some bugs

rust_src/src/wrterm.rs
=> webrender: implement xw-color-values. Fixes #129.

rust_src/crates/lisp/src/remacs_sys.rs, rust_src/src/webrender_backend/keyboard.rs
=> webrender: fix Modifiers build error #138.

README.md
=> Add note about the last commit merged from native-comp

getting-started.md
Updating filewatcher example to be more idiomatic
=> Update filewatcher example

configure.ac, rust_src/Cargo.lock, rust_src/Cargo.toml.in, rust_src/src/javascript.rs, test/js/basicLisp.js
https://github.com/emacs-ng/emacs-ng/issues/118
I'm going to mark this as WIP just because I want to test it as my main driver for a few days to test for stability. This code works, tests pass, and reviews are welcome.
=> Upgrading emacs-ng to deno-v1.7.2

.github/workflows/test.yml
Since at least the JS integration tests are working now, we might as well add those to our CI flow IMO.
=> Adding JS Tests to CI Flow

rust_src/src/javascript.rs, test/js/basicLisp.js, test/js/bootstrap.el, test/js/errors.js, test/js/helloWorld.js, test/js/main.js, test/js/webAsm.js, test/js/webWorkers.js
I've always included a few improvements to the testing framework, like naming out tests instead of Test 1, 2, 3..
=> Fixing issue where the event loop wouldn't tick in --batch mode

rust_src/src/webrender_backend/font.rs
=> webrender: fix postscript not found error #126

rust_src/src/wrterm.rs, src/image.c, src/wrterm.h
=> add PUT_PIXEL

README.md
Addressing https://github.com/emacs-ng/emacs-ng/issues/187
=> Removing fib benchmark from README

.github/workflows/test.yml, docs/getting-started.md
=> Include build for macOS

rust_src/crates/emacs/src/number.rs
=> define consts from number.rs for macOS too

build_emacs_ng.sh, default.nix, docs/getting-started.md, flake.lock, flake.nix, nix/librusty_v8.nix, shell.nix
- DONE for Emacs-Ng via Nix-build
https://github.com/GTrunSec/emacsNg-overlay/blob/main/flake.nix
=> Fix install facilities and update Nix exp

.github/workflows/release.yml, build_emacs_ng.sh, rust_src/src/webrender_backend/event.rs, rust_src/src/webrender_backend/font.rs, rust_src/src/webrender_backend/frame.rs, rust_src/src/webrender_backend/input.rs, rust_src/src/webrender_backend/term.rs, rust_src/src/wrterm.rs
=> ci: Also build release for webrender version

.gitignore, docs/getting-started.md, docs/nix-develop.md, flake.lock, flake.nix, mkdocs.yml, nix/commands.toml, nix/rust.nix
@ericdallo  May you help me to modify and enrich this doc. thanks
@DavidDeSimone please check this doc that pretty simple.
=> docs: add rust dev environment with nix and direnv

.github/workflows/test.yml, rust_src/src/webrender_backend/event.rs, rust_src/src/webrender_backend/font.rs, rust_src/src/webrender_backend/frame.rs, rust_src/src/webrender_backend/input.rs, rust_src/src/webrender_backend/term.rs, rust_src/src/wrterm.rs
There are a few more CI-related tasks to take place in the future. #196 #197
However, the slow build speed is hopeless.
Compared to the last successful build, the following improvements have been made:
https://github.com/emacs-ng/emacs-ng/actions/runs/720012839
https://github.com/black7375/emacs-ng/actions/runs/724927062
- Ubuntu: `26m 6s` => `10m 51s`
- MacOS: `39m 7s` => `16m 17s`
---
#204 be resolved first. (Mac Build Fail)
=> Efficient build CI

.github/ISSUE_TEMPLATE/bug_report.md
- bug label
- configure template
- OS info command: uname -a
=> Uppdate issue template

rust_src/src/webrender_backend/term.rs
=> webrender: fixes #218

.envrc, flake.lock, flake.nix, nix/commands.toml, nix/rust.nix
Because of instability #227, The flag of webreand is still under development mode.
So, the building process disabled the webrender by default.
=> Nix: add build option of webrender

rust_src/src/webrender_backend/draw_canvas.rs, rust_src/src/webrender_backend/output.rs
Fixes scrolling artifacts issue.
=> webrender: fix HiDPI display issue (#227).

README.md, docs/faq.md, docs/getting-started.md, docs/main-features.md
Hi :wave: 
this PR fixes some links by using internal links with relative path
=> Fix some links in docs

rust_src/src/webrender_backend/font.rs
=> webrender: implement `list_family`

rust_src/src/webrender_backend/draw_canvas.rs
* Fix cursor length
* Fix fringe display bug
=> Webrender: fix minor display bugs.

lisp/mwheel.el, rust_src/src/webrender_backend/cursor.rs, rust_src/src/webrender_backend/input.rs, rust_src/src/webrender_backend/output.rs, rust_src/src/webrender_backend/term.rs, src/wrgui.h
=> webrender: show different cursor types over different elements.

rust_src/src/javascript.rs
:wave:  this PR fixes the issue  [#175 ](https://github.com/emacs-ng/emacs-ng/issues/175) by using the re-exported `anyhow::Error` by Deno.
I'm not sure yet how to test regressions or eventual breaking changes caused by this.  I tried to eval some scripts and seems fine.
If you have specific tests to run let me know :)
Thanks
=> Replace io::Error with anyhow::Error

rust_src/build.rs, rust_src/crates/js/src/javascript.rs, rust_src/crates/ng_async/src/ng_async.rs, rust_src/crates/ng_async/src/parsing.rs, rust_src/remacs-lib/docfile.rs, rust_src/src/lib.rs, src/Makefile.in
=> generate rust globals

rust_src/crates/webrender/src/cursor.rs, rust_src/crates/webrender/src/draw_canvas.rs, rust_src/crates/webrender/src/frame.rs, rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/wrterm.rs
=> Webrender: rework doc-view pdf functionality

Makefile.in, docs/handbook/tests.md
I've added two lines of docs about `rustfmt` target. I'm not sure the `tests` section is the right place.
I was not sure where to place this info :)
=> update rustfmt target

README.md, docs/handbook/getting-started.md, docs/handbook/types.md, mkdocs.yml
I started writing an overview for new contributors. Somebody asked in gitter and I think we need more docs to help newcomers.
=> add contributor's guide to handbook

.gitignore
This really annoys me, but it seems I'm the only one with this issue ?
=> ignore build-aux/config.guess and build-aux/config.sub

rust_src/crates/webrender/src/color.rs
=> webrender: fix length 4 color string crash

rust_src/crates/lsp_json/src/parsing.rs
=> return serde_json::Value::Null when nilp

.gitmodules, autogen.sh, lisp/Makefile.in
=> add straight.el/use-package as git submodules

rust_src/crates/webrender/Cargo.toml, rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/util.rs
=> webrender: set app_id for wayland

rust_src/Cargo.lock, rust_src/crates/emacs/src/glyph.rs, rust_src/crates/webrender/src/draw_canvas.rs
=> webrender: render composite glyph.

rust_src/crates/webrender/src/font.rs
=> webrender: fix font crash #359.

docs/build/building.md, docs/build/docker.md, docs/build/nix-develop.md, docs/handbook/build.md, docs/handbook/getting-started.md, docs/handbook/lisp-fn.md, docs/handbook/tests.md, docs/handbook/types.md, docs/js/architecture.md, docs/js/getting-started.md, docs/js/main-features.md, docs/js/using-deno.md, docs/webrender.md
Small documentation updates, such as:
- spelling
- harmonization of spelling
=> Harmonize and fix small items in descriptions

flake.lock, flake.nix, nix/_sources/generated.nix
=> Nix: Bumpup #371

rust_src/Cargo.lock, rust_src/crates/webrender/Cargo.toml, rust_src/crates/webrender/src/event_loop.rs, rust_src/crates/webrender/src/frame.rs, rust_src/crates/webrender/src/future.rs, rust_src/crates/webrender/src/lib.rs, rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/term.rs, src/process.c, src/wrterm.h
=> webrender: run event_loop in main thread.

rust_src/crates/webrender/src/event_loop.rs, rust_src/crates/webrender/src/term.rs
=> webrender: support window close request.

rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/wrterm.rs
=> webrender: fix x_display_monitor_attributes_list crash.

Makefile.in, README.md, admin/notes/git-submodule, lib-src/Makefile.in, lisp/Makefile.in, lisp/emacs-lisp/emacs-ng-init.el, lisp/emacs-lisp/emacs-ng.el, lisp/loadup.el, lisp/startup.el, src/Makefile.in
Context https://github.com/emacs-ng/emacs-ng/issues/348#issuecomment-890514436
=> Automate straight.el bootstrapping process

rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/util.rs
This is a follow-up change for #355
=> webrender: use invocation_name as app_id

rust_src/crates/lsp_json/src/parsing.rs
https://github.com/emacs-lsp/lsp-mode/pull/2978
=> add function lsp_async_send_notification

configure.ac
=> build: rust debug build fix

rust_src/crates/webrender/src/draw_canvas.rs
=> webrender: fix draw_image_glyph crash

.github/workflows/test.yml, rust_src/crates/emacs/build.rs.in
=> fix(build): fix macOS build.

Cargo.lock, rust_src/crates/emacs/Cargo.toml, rust_src/crates/emacs/build.rs.in, rust_src/crates/emacs/src/list.rs, rust_src/crates/emacs/src/symbol.rs, rust_src/crates/lisp_macros/lib.rs, rust_src/crates/webrender/src/event.rs, rust_src/crates/webrender/src/input.rs
=> chore(deps): update `bindgen` to `0.64`

.github/workflows/test.yml, configure.ac, rust_src/crates/webrender/Cargo.in
=> fix(build): make webrender x11 an opt-out feature #467

.github/workflows/checks.yaml, flake.nix
Add emacsng-noNativeComp and run emacsng-noNativeComp for CI check
=> feat(nix): add emacsng-noNativeComp

rust_src/crates/webrender/src/cursor.rs, rust_src/crates/webrender/src/wrterm.rs
=> Invalid cursor fix

Cargo.lock, configure.ac, rust_src/crates/webrender/Cargo.in, rust_src/crates/webrender/src/event_loop.rs, rust_src/crates/webrender/src/gl/context.rs, rust_src/crates/webrender/src/gl/context_impl/glutin.rs, rust_src/crates/webrender/src/gl/context_impl/surfman.rs, rust_src/crates/webrender/src/lib.rs, rust_src/crates/webrender/src/output.rs
The glutin part is written by John Maximilian @2e0byo
=> feat(WR): add support for initialize GL using glutin

rust_src/crates/webrender/src/gl/context_impl/glutin.rs, rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/term.rs
Missing a [patch](https://github.com/2e0byo/emacs-ng/commit/2b8355e403d5726607bf16157ba78c4e66145426) from @2e0byo
=> Fix emacs crash when creating new frame with glutin

docs/handbook/getting-started.md
That way other people won't be relying on grep like I was :D
=> doc: logging.

Cargo.lock, rust_src/crates/webrender/Cargo.toml, rust_src/crates/webrender/src/display_info.rs, rust_src/crates/webrender/src/draw_canvas.rs, rust_src/crates/webrender/src/font.rs, rust_src/crates/webrender/src/frame.rs, rust_src/crates/webrender/src/input.rs, rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/window_system/winit/frame.rs, rust_src/crates/webrender/src/window_system/winit/output.rs, rust_src/crates/webrender/src/window_system/winit/term.rs
=> Fix winit scaling issues

.github/workflows/pull-upstream.yml
=> Add CI to automatically sync upstream master

.github/workflows/pull-upstream.yml, README.md
The PRs are submitted by actions-user. The first PR will need approval.
=> Run check/test for pull upstream PRs

docs/webrender.md
=> docs: flickering with glutin/tao on linux.

Cargo.in, Cargo.lock, configure.ac, lisp/image.el, rust_src/crates/emacs/Cargo.toml, rust_src/crates/emacs/src/eval_macros.rs, rust_src/crates/emacs/src/lglyph.rs, rust_src/crates/emacs/src/lib.rs, rust_src/crates/emacs/src/lisp.rs, rust_src/crates/emacs/src/number.rs, rust_src/crates/emacs/src/vector.rs, rust_src/crates/webrender/Cargo.toml, rust_src/crates/webrender/src/color.rs, rust_src/crates/webrender/src/draw_canvas.rs, rust_src/crates/webrender/src/font.rs, rust_src/crates/webrender/src/font_db.rs, rust_src/crates/webrender/src/fringe.rs, rust_src/crates/webrender/src/image.rs, rust_src/crates/webrender/src/image_cache.rs, rust_src/crates/webrender/src/lib.rs, rust_src/crates/webrender/src/output.rs, rust_src/crates/webrender/src/term.rs, src/image.c
- Add svg and all formats that image_rs supports by default.
- Add glyph automatic composition
=> Add more image formats support

Cargo.in, Cargo.lock, configure.ac, rust_src/crates/webrender/Cargo.toml, rust_src/crates/webrender/src/event_loop.rs, rust_src/crates/webrender/src/image.rs, rust_src/crates/webrender/src/image_cache.rs, rust_src/crates/webrender/src/lib.rs, rust_src/crates/webrender/src/window_system/winit/term.rs, rust_src/crates/webrender/src/wrterm.rs
=> Avoid creating winit's event_loop from Lisp.

lisp/term/wr-win.el
=> Fix winitterm emacsclient -cn

Cargo.in, Cargo.lock, rust_src/crates/emacs/src/display_traits/glyph_string.rs, rust_src/crates/emacs/src/display_traits/mod.rs, rust_src/crates/emacs/src/frame.rs, rust_src/crates/gl-renderer/src/glyph.rs, rust_src/crates/lisp_macros/Cargo.toml, rust_src/crates/lisp_macros/function.rs, rust_src/crates/lisp_macros/lib.rs, rust_src/crates/lisp_util/Cargo.toml, rust_src/crates/lisp_util/attributes.rs, rust_src/remacs-lib/Cargo.toml, rust_src/remacs-lib/docfile.rs
update rust crates syn/darling/quote/proc-macro2 to latest
close #142
=> Update sync darling etc

lib-src/Makefile.in, src/Makefile.in
=> Fix doc for lisp fn defined in Rust 

crates/winit-term/src/term.rs
Code from C sometimes set timeout to 10000s. No idea how to reason about that.
Manually set a maximum timeout for winit_select.
=> Set a maximum timeout for winit_select

crates/emacs-sys/src/frame.rs, lisp/term/winit-win.el
=> Prevent use parent-frame parameter on winit for now
